---
title: "About"
---

## about me

- 🏊 I was a [swimmer (lane #5)](https://www.youtube.com/watch?v=fN7sJPFeJcw);
- 🎬 I love watching [musical videos](https://bit.ly/avc-musicamundial);
- 🇵🇪 I have a playlist of [peruvian music](https://bit.ly/avc-musicaperuana);
- 🗃️ I store [artmospheres](https://www.instagram.com/recursivoo/) in a couple [more](https://www.youtube.com/channel/UCvbhEkxtIVA9ldfhqDFALTA/playlists);
- 🎼 I occasionally [play](https://soundcloud.com/avallecam) guitar🎸|piano🎹;
- 🖤 I read a manga called [berserk](https://readberserk.com/chapter/berserk-chapter-a0/);
- 🍃 I watch an anime called [naruto](https://www.crunchyroll.com/series/GY9PJ5KWR/naruto), previously [avatar](https://www.netflix.com/gb/title/70142405);
- 🎨 I appreciate visiting [art galleries](https://coleccion.mali.pe/collections), [unexpected](https://maclima.pe/project/visitante-fernando-de-szyszlo/) findings [occur](https://www.metmuseum.org/es/art/collection/search/267838);
- 🥦 I got curious on physical biology after: [goodwin](https://libgen.rs/book/index.php?md5=CBFF641AD61645A284EE4566EB2B0146), [bejan](https://libgen.rs/book/index.php?md5=F9D8AF5DCDF3C74ED2C34A56C7522E22), [leibler](https://journals.aps.org/prx/abstract/10.1103/PhysRevX.5.041014);
- 🌩️ I enjoy reading dialectical materialism: [politzer](https://libgen.rs/book/index.php?md5=BDA5E8E26C125758A4C809D3C74F2136), [fromm](https://libgen.rs/book/index.php?md5=2B4A32A41996AEFB7D810F90A67EAEE2), [engels](https://libgen.rs/book/index.php?md5=64BA70A56CE5241A442C2056B3766995);
- 🔥 I love reading poetic literature: [oswaldo reynoso](https://www.librosperuanos.com/libros/detalle/7026/El-Goce-de-la-Piel), [martin adan](https://www.librosperuanos.com/libros/detalle/15881/La-casa-de-carton);
- 🎲 I like listening to [radiohead](https://youtu.be/I4pezRt9boY), [apparat](https://youtu.be/NOol5V4Tlk8), [niños sin](https://youtu.be/S5vKPHigWqY) [smartphones](https://youtu.be/QI9mksVqivg);
- 🔮 I also like listening to [domΔ](https://youtu.be/9nNOWTDvvzk) and the [peruvian avant trap](https://youtube.com/playlist?list=PLDHw5KzS-qvJfGR6wuhU-z5XITknspxel)!
- 🍥 I am [learning](https://www.a11yproject.com/) to design [accessible](https://user2021.r-project.org/participation/accessibility/) outputs.
- 🌠 I feed a wishlist in [elfster](https://www.elfster.com/profile/097d261f-1196-45a1-a4b4-12e0b245ce2d/wish-lists/be4efeaf-b9e7-465d-bcac-65ef129be519/);

## avallecam

- 🌞 Stands for **a**ndree **valle** **cam**pos.
- 💕 I intentionally used [**cam**](https://www.mychinaroots.com/surnames/detail?word=Campos) because [#tusan](http://www.tusanaje.org/ser-tusan/)
