---
title: "Bio"
---

## now

- 🎉 Community building and Training at [the Epiverse-TRACE](https://data.org/initiatives/epiverse/);
- 🍎 Crafted a [GeoViz](https://thegraphcourses.org/courses/geospatial-visualization/) with `R` lesson for [The GRAPH Network](https://thegraphcourses.org/courses-portal/);
- 📦 Crafted last [serosurvey](https://avallecam.github.io/serosurvey/) package ✨;
- ⭐ Coordinator in a last [outbreak analysis](https://www.reconlearn.org/topics/spanish.html) [course](https://www.dge.gob.pe/portalnuevo/informativo/prensa/curso-internacional-en-analisis-de-brotes-modelamiento-y-respuesta-en-salud-publica/) in [latinamerica](https://twitter.com/avallecam/status/1413682203041701889?s=20);

## bio

- 🏠 I have trained in *scientific computing* practices for **genetics and biotech**, and applied statistics in **epidemiology**;
- 📜 I did my [MSc](https://github.com/avallecam/movmal) research about human mobility and malaria history in the peruvian amazon (**UPCH, 2018**);
- 📜 I did my [BSc](https://github.com/avallecam/abnomic) research about antibody responses and severe vivax malaria with protein microarrays (**UNMSM, 2015**);

## skills

- ⚙️ I am a proficient **`R` user**, expert `tidy` data **wrangler** and `ggplot2` **visualization** enthusiast.
- ☁️ I am fluid with `bash` for **automation**, `shh` for **remote** computing, and `shiny` for reactive **dashboards**.
- 📀 I have *tried to* make **statistical workflows** with omic, serological, gps, health service, and outbreak **spatio-temporal** data;
- 🥤 I have complemented my **training** with awesome communities: [ictp-saifr](https://www.ictp-saifr.org/v-southern-summer-school-on-mathematical-biology/), [codata-rda](https://www.datascienceschools.org/), [recon](https://www.repidemicsconsortium.org/), [metadocencia](https://www.metadocencia.org/cursos/), [carpentries](https://carpentries.github.io/instructor-training/);

## contact

- 💬 Ping [me](https://www.linkedin.com/in/avallecam/) about **`R` in epidemiology**, **data science education**, and **applied biostatistics**;
- 📫 Reach me: avallecam at gmail;
- 🐤 Tweet me: [`@avallecam`](https://twitter.com/avallecam).
